# Generated by Django 5.2.8 on 2025-12-16 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_subject_faculty'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'subject', 'date')},
        ),
    ]
